apiVersion: apps/v1
kind: Deployment
metadata:
  name: oref-ws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oref-ws
  template:
    metadata:
      labels:
        app: oref-ws
    spec:
      containers:
        - name: oref-ws
          image: reblink17/oref:v1
          resources:
            limits:
              cpu: "0.5"
              memory: "256Mi"
            requests:
              cpu: "0.25"
              memory: "128Mi"
          ports:
            - containerPort: 3000
